### ISSUE TITLE
Forecast is not working properly after last update

### ISSUE THREAD

**Issue by woody4165** [r-renato/ha-climacell-weather#11]
Hi

After last update, forecast has changed and I've changed the configuration in sensor.yaml

Daily forecast gives always unknown and now the fields name that previously were 0d, 1d, 2d... now are 0_d, 1_d, 2_d

This is my actual configuration

```
    monitored_conditions:
      realtime:
        conditions:
          - temperature
          - feels_like
          - dewpoint
          - humidity
          - wind_speed
          - wind_direction
          - wind_gust
          - pressure
          - precipitation
          - precipitation_type
#          - precipitation_probability
#          - precipitation_accumulation
          - sunset
          - sunrise
          - visibility
          - cloud_cover
          - cloud_base
          - cloud_ceiling
#          - satellite_cloud
          - surface_shortwave_radiation
          - moon_phase
          - weather_condition
#          - weather_groups
          - pm25
          - pm10
          - o3
          - no2
          - co
          - so2
          - epa_aqi
          - epa_primary_pollutant
          - epa_health_concern
#          - china_aqi
#          - china_primary_pollutant
#          - china_health_concern
          - pollen_tree
          - pollen_weed
          - pollen_grass
          - road_risk_score
#          - road_risk
          - road_risk_confidence
          - road_risk_conditions
          - fire_index
        update: auto
        scan_interval:
          # At least one of these must be specified:
          days: 0
          hours: 0
          minutes: 30
          seconds: 0
          milliseconds: 0
      daily:
        forecast_observations: 5
        conditions:
          - temperature
          - feels_like
#          - dewpoint
          - humidity
          - wind_speed
          - wind_direction
#          - wind_gust
          - pressure
          - precipitation
#          - precipitation_type
          - precipitation_probability
          - precipitation_accumulation
          - sunset
          - sunrise
          - visibility
#          - cloud_cover
#          - cloud_base
#          - cloud_ceiling
#          - satellite_cloud
#          - surface_shortwave_radiation
#          - moon_phase
          - weather_condition
#          - weather_groups
#          - pm25
#          - pm10
#          - o3
#          - no2
#          - co
#          - so2
#          - epa_aqi
#          - epa_primary_pollutant
#          - epa_health_concern
#          - china_aqi
#          - china_primary_pollutant
#          - china_health_concern
#          - pollen_tree
#          - pollen_weed
#          - pollen_grass
#          - road_risk_score
#          - road_risk
#          - road_risk_confidence
#          - road_risk_conditions
#          - fire_index
        scan_interval:
          # At least one of these must be specified:
          days: 0
          hours: 3
          minutes: 0
          seconds: 0
          milliseconds: 0
        exclude_interval:
          1:
            - "10:00"
            - "12:00"
          2:
            - "00:00"
            - "06:30"
      hourly:
        forecast_observations: 5
        conditions:
          - temperature
          - feels_like
          - dewpoint
          - humidity
          - wind_speed
          - wind_direction
          - wind_gust
          - pressure
          - precipitation
          - precipitation_type
          - precipitation_probability
#          - precipitation_accumulation
          - sunset
          - sunrise
          - visibility
          - cloud_cover
          - cloud_base
          - cloud_ceiling
#          - satellite_cloud
          - surface_shortwave_radiation
          - moon_phase
          - weather_condition
#          - weather_groups
          - pm25
          - pm10
          - o3
          - no2
          - co
          - so2
          - epa_aqi
          - epa_primary_pollutant
          - epa_health_concern
#          - china_aqi
#          - china_primary_pollutant
#          - china_health_concern
          - pollen_tree
          - pollen_weed
          - pollen_grass
          - road_risk_score
#          - road_risk
          - road_risk_confidence
          - road_risk_conditions
#          - fire_index
        scan_interval:
          # At least one of these must be specified:
          days: 0
          hours: 1
          minutes: 0
          seconds: 0
          milliseconds: 0
      nowcast:
        timestep: 5
        forecast_observations: 5
        conditions:
          - temperature
          - feels_like
          - dewpoint
          - humidity
          - wind_speed
          - wind_direction
          - wind_gust
          - pressure
          - precipitation
          - precipitation_type
#          - precipitation_probability
#          - precipitation_accumulation
          - sunset
          - sunrise
          - visibility
          - cloud_cover
          - cloud_base
          - cloud_ceiling
#          - satellite_cloud
          - surface_shortwave_radiation
#          - moon_phase
          - weather_condition
#          - weather_groups
          - pm25
          - pm10
          - o3
          - no2
          - co
          - so2
          - epa_aqi
          - epa_primary_pollutant
          - epa_health_concern
#          - china_aqi
#          - china_primary_pollutant
#          - china_health_concern
          - pollen_tree
          - pollen_weed
          - pollen_grass
          - road_risk_score
#          - road_risk
          - road_risk_confidence
          - road_risk_conditions
#          - fire_index
        scan_interval:
          # At least one of these must be specified:
          days: 0
          hours: 0
          minutes: 5
          seconds: 0
          milliseconds: 0

```

This is what I get

![Schermata 2020-07-01 alle 11 50 36](https://user-images.githubusercontent.com/6501444/86230282-2abe7b80-bb91-11ea-9fc6-4d46b61f3e61.png)

**Comment by alesoft73** [comment]
I too the sensor about day is unknown ;)
GRAZIE COME SEMPRE!

**Comment by alesoft73** [comment]
After your update sensor date is ok but :
_pollen_tree
_pollen_weed
... unknown ;)
Many thanks

**Comment by r-renato** [comment]
> Hi
> 
> After last update, forecast has changed and I've changed the configuration in sensor.yaml
> 
> Daily forecast gives always unknown and now the fields name that previously were 0d, 1d, 2d... now are 0_d, 1_d, 2_d
> 
> This is my actual configuration
> 
> ```
>     monitored_conditions:
>       realtime:
>         conditions:
>           - temperature
>           - feels_like
>           - dewpoint
>           - humidity
>           - wind_speed
>           - wind_direction
>           - wind_gust
>           - pressure
>           - precipitation
>           - precipitation_type
> #          - precipitation_probability
> #          - precipitation_accumulation
>           - sunset
>           - sunrise
>           - visibility
>           - cloud_cover
>           - cloud_base
>           - cloud_ceiling
> #          - satellite_cloud
>           - surface_shortwave_radiation
>           - moon_phase
>           - weather_condition
> #          - weather_groups
>           - pm25
>           - pm10
>           - o3
>           - no2
>           - co
>           - so2
>           - epa_aqi
>           - epa_primary_pollutant
>           - epa_health_concern
> #          - china_aqi
> #          - china_primary_pollutant
> #          - china_health_concern
>           - pollen_tree
>           - pollen_weed
>           - pollen_grass
>           - road_risk_score
> #          - road_risk
>           - road_risk_confidence
>           - road_risk_conditions
>           - fire_index
>         update: auto
>         scan_interval:
>           # At least one of these must be specified:
>           days: 0
>           hours: 0
>           minutes: 30
>           seconds: 0
>           milliseconds: 0
>       daily:
>         forecast_observations: 5
>         conditions:
>           - temperature
>           - feels_like
> #          - dewpoint
>           - humidity
>           - wind_speed
>           - wind_direction
> #          - wind_gust
>           - pressure
>           - precipitation
> #          - precipitation_type
>           - precipitation_probability
>           - precipitation_accumulation
>           - sunset
>           - sunrise
>           - visibility
> #          - cloud_cover
> #          - cloud_base
> #          - cloud_ceiling
> #          - satellite_cloud
> #          - surface_shortwave_radiation
> #          - moon_phase
>           - weather_condition
> #          - weather_groups
> #          - pm25
> #          - pm10
> #          - o3
> #          - no2
> #          - co
> #          - so2
> #          - epa_aqi
> #          - epa_primary_pollutant
> #          - epa_health_concern
> #          - china_aqi
> #          - china_primary_pollutant
> #          - china_health_concern
> #          - pollen_tree
> #          - pollen_weed
> #          - pollen_grass
> #          - road_risk_score
> #          - road_risk
> #          - road_risk_confidence
> #          - road_risk_conditions
> #          - fire_index
>         scan_interval:
>           # At least one of these must be specified:
>           days: 0
>           hours: 3
>           minutes: 0
>           seconds: 0
>           milliseconds: 0
>         exclude_interval:
>           1:
>             - "10:00"
>             - "12:00"
>           2:
>             - "00:00"
>             - "06:30"
>       hourly:
>         forecast_observations: 5
>         conditions:
>           - temperature
>           - feels_like
>           - dewpoint
>           - humidity
>           - wind_speed
>           - wind_direction
>           - wind_gust
>           - pressure
>           - precipitation
>           - precipitation_type
>           - precipitation_probability
> #          - precipitation_accumulation
>           - sunset
>           - sunrise
>           - visibility
>           - cloud_cover
>           - cloud_base
>           - cloud_ceiling
> #          - satellite_cloud
>           - surface_shortwave_radiation
>           - moon_phase
>           - weather_condition
> #          - weather_groups
>           - pm25
>           - pm10
>           - o3
>           - no2
>           - co
>           - so2
>           - epa_aqi
>           - epa_primary_pollutant
>           - epa_health_concern
> #          - china_aqi
> #          - china_primary_pollutant
> #          - china_health_concern
>           - pollen_tree
>           - pollen_weed
>           - pollen_grass
>           - road_risk_score
> #          - road_risk
>           - road_risk_confidence
>           - road_risk_conditions
> #          - fire_index
>         scan_interval:
>           # At least one of these must be specified:
>           days: 0
>           hours: 1
>           minutes: 0
>           seconds: 0
>           milliseconds: 0
>       nowcast:
>         timestep: 5
>         forecast_observations: 5
>         conditions:
>           - temperature
>           - feels_like
>           - dewpoint
>           - humidity
>           - wind_speed
>           - wind_direction
>           - wind_gust
>           - pressure
>           - precipitation
>           - precipitation_type
> #          - precipitation_probability
> #          - precipitation_accumulation
>           - sunset
>           - sunrise
>           - visibility
>           - cloud_cover
>           - cloud_base
>           - cloud_ceiling
> #          - satellite_cloud
>           - surface_shortwave_radiation
> #          - moon_phase
>           - weather_condition
> #          - weather_groups
>           - pm25
>           - pm10
>           - o3
>           - no2
>           - co
>           - so2
>           - epa_aqi
>           - epa_primary_pollutant
>           - epa_health_concern
> #          - china_aqi
> #          - china_primary_pollutant
> #          - china_health_concern
>           - pollen_tree
>           - pollen_weed
>           - pollen_grass
>           - road_risk_score
> #          - road_risk
>           - road_risk_confidence
>           - road_risk_conditions
> #          - fire_index
>         scan_interval:
>           # At least one of these must be specified:
>           days: 0
>           hours: 0
>           minutes: 5
>           seconds: 0
>           milliseconds: 0
> ```
> 
> This is what I get
> 
> ![Schermata 2020-07-01 alle 11 50 36](https://user-images.githubusercontent.com/6501444/86230282-2abe7b80-bb91-11ea-9fc6-4d46b61f3e61.png)

hi, the component is changed, some sensors have  changed name. Each service type (realtime, nowcast, hourly, daily) have his scan and his exclusion interval.  Read the readme and edit your yaml file, then make the changes to your lovelace configuration.

Thanks,
Renato

**Comment by r-renato** [comment]
> After your update sensor date is ok but :
> _pollen_tree
> _pollen_weed
> ... unknown ;)
> Many thanks

Check your exclusion interval for the services ;)

Grazie, ciao.
Renato

**Comment by woody4165** [comment]
> > After your update sensor date is ok but :
> > _pollen_tree
> > _pollen_weed
> > ... unknown ;)
> > Many thanks
> 
> Check your exclusion interval for the services ;)
> 
> Grazie, ciao.
> Renato

I have also _unknown_ value for `pollen_tree` and `pollen_weed` instead `pollen_grass` is working
I have no exclusion interval for any service.


> hi, the component is changed, some sensors have changed name. Each service type (realtime, nowcast, hourly, daily) have his scan and his exclusion interval. Read the readme and edit your yaml file, then make the changes to your lovelace configuration.
> 
> Thanks,
> Renato

I notice that some components (min and max) have changed naming
previously they were, for example, `min_temperature_0d` and now `temperature_min_0d` same for max precipitation.


Thanks!

**Comment by alesoft73** [comment]
> 
> 
> > After your update sensor date is ok but :
> > _pollen_tree
> > _pollen_weed
> > ... unknown ;)
> > Many thanks
> 
> Check your exclusion interval for the services ;)
> 
> Grazie, ciao.
> Renato

Grande Renato :-)
The sensor isn't in exclusion.
          - pollen_tree (work perfect)
          - pollen_weed (unknown)
          - pollen_grass (unknown)

I use your configuration in example readme.md .
Regards!

**Comment by woody4165** [comment]
Really strange that for me is working `pollen_grass` and for @alesoft73 is working `pollen_tree`..


Grazie Renato!

**Comment by alesoft73** [comment]
> 
> 
> Really strange that for me is working `pollen_grass` and for @alesoft73 is working `pollen_tree`..
> 
> Grazie Renato!

I think the problem isn't in a sensor...
now il all unknown

- pollen_tree (unknown)
- pollen_weed (unknown)
- pollen_grass (unknown)

:-)))))

**Comment by r-renato** [comment]
Climacell data provider say:  _pollen index for trees, weed and  grass is a **number (or null if not in season)**_.
See th details here: [](https://developer.climacell.co/v3/reference#data-layers-pollen)

Put the component log to debug level and post here the details if you want help with this analysis.

```
# Logging
logger:
  logs:
    custom_components.climacell: debug
```

Thanks,
Renato
