### ISSUE TITLE
Missing _0d in forcast

### ISSUE THREAD

**Issue by guice** [r-renato/ha-climacell-weather#16]
According to the docs:

> daily
   [...]
    forecast_observations
        (integer)(Optional)
        Number of days for which you would like to receive forecast. **The valid values are numbers starting from 1 to 15.** Any condition from monitored_conditions (forecast) will generate a sensor with entity_id <condition>_<day>d.
        Default value:
        5

I do only see 1-_n_ values, but your weather card shows a `_0d` setting:

https://github.com/r-renato/ha-card-weather-conditions#current-layer-example-of-card-setup
```yaml
    forecast:
      temperature_high:
        day_1: sensor.cc_test_max_temperature_0d
      temperature_low:
        day_1: sensor.cc_test_min_temperature_0d
```

Where do I get Zero day, "Today", min and max values?
