### ISSUE TITLE
Question on new API

### ISSUE THREAD

**Issue by julianrinaldi** [r-renato/ha-climacell-weather#38]
I spent the morning setting up a Road Risk conditions card, and then updated to the new version, and they all broke. I now realize the API has changed. I'm looking at the API documents and I'm not seeing anything for road conditions. Is this now gone?

**Comment by mfabiani53** [comment]
I think we need to know __all__ the breaking changes after the latest update of the integration.... I will wait these before updating....

**Comment by r-renato** [comment]
Is this issue still there?

**Comment by julianrinaldi** [comment]
Yes. Actually all of my sensors are throwing errors and showing up as "Unknown"
2021-01-25 16:12:12 WARNING (SyncWorker_27) [custom_components.climacell.sensor] TimelineSensor.update - Provider has no data for: cc Climacell Precipitation 0d

I have signed up for and am using the V4 API Key

```
- platform: climacell
  api_key: !secret climacell_api_key
  name: Climacell
  timelines:
    - name: ""
      fields:
        - temperature
        - wind_direction
        - precipitation
        - precipitation_type
        - wind_speed
        - wind_direction
        - weather_condition
        - pollen_tree
        - pollen_weed
        - pollen_grass
        - road_risk
        - road_risk_conditions
        - road_risk_confidence
      update: auto
      forecast_observations: 5
      timestep: "15m"
      scan_interval:
          minutes: 5
```

**Comment by InToSSH** [comment]
I have exactly the same problem. It worked for a bit, but only some sensors. The log is full of errors:
```
2021-01-26 01:14:02 WARNING (SyncWorker_6) [custom_components.climacell.sensor] TimelineSensor.update - Provider has no data for: cc Home Daily Temperature 0d
2021-01-26 01:14:02 WARNING (SyncWorker_2) [custom_components.climacell.sensor] TimelineSensor.update - Provider has no data for: cc Home Daily Temperature 1d
2021-01-26 01:14:02 WARNING (SyncWorker_4) [custom_components.climacell.sensor] TimelineSensor.update - Provider has no data for: cc Home Daily Temperature 2d
```

**Comment by cbergmann** [comment]
@InToSSH that is correct. One timeline is one request to the API with all the fields. This is to reduce the number of requests as this is the limiting factor of the free tier. But if the request fails for some reason there is no data for any field of that timeline. 

@julianrinaldi is the problem still there with the current version?

**Comment by julianrinaldi** [comment]
Yes, I'm still having the issue of all my sensors showing up as unknown. I'm on the latest version. Here is my YAML. Is there anything wrong with it?

```
- platform: climacell
  api_key: !secret climacell_api_key
  name: Climacell
  timelines:
    - name: ""
      fields:
        - temperature
        - wind_direction
        - precipitation
        - precipitation_type
        - wind_speed
        - wind_direction
        - weather_condition
        - pollen_tree
        - pollen_weed
        - pollen_grass
        - road_risk
        - road_risk_conditions
        - road_risk_confidence
      update: auto
      forecast_observations: 5
      scan_interval:
          minutes: 5
```
