### ISSUE TITLE
Adding the field "moon_phase" breaks most of the sensors (V4)

### ISSUE THREAD

**Issue by romquenin** [r-renato/ha-climacell-weather#43]
Thank you @r-renato for your great work !
The last update brought me back 99% of the sensors but unfortunately it's seems impossible to add the moon_phase, when i do so most of the sensors are reporting unknown states.
Has you didn't had the field in your configuration exemple there is maybe some issues with this particular sensor.
I hope you will find a way to solve this.
Keep it up, this component and the dedicated card you have created are amazing !

**Comment by the0ckid82** [comment]
Can confirm, i have tried both the v3 field  `moon_phase` and the v4 `moonPhase` both break every other sensor but if you remove the moon phase everything else works

**Comment by fa-ve** [comment]
same issue, did try all possible ways

**Comment by r-renato** [comment]
The moonPhase sensor work for timestep: 1d/15d 

```
      - name: "" #Daily
        timestep: "1d"
        forecast_observations: 5
        fields:
          - moonPhase
```
