### ISSUE TITLE
Temperature and Feels Like Temperature

### ISSUE THREAD

**Issue by nytram-md** [r-renato/ha-climacell-weather#44]
Hi.

Great work and cant have been easy the last week or so. So thank you.

I have V4 working and not working but currently working but this time my temperature and feels like temperatures are back to been the same temperatures. This was working at the start of V4 api and had different temperatures but last update put them back to being the same. Is this a bug ?

Met Office in UK is saying for eg 6c but feels like 2 but Climacell is saying both temperature and feels like are both 5.71c

Thanks 

Martyn

**Comment by cbergmann** [comment]
that is strange, I see different values for the two fields for my location for my daily timeline configured like the following:
```
- fields:
        - temperatureMax
        - temperatureMin
        - temperatureApparentMax
        - temperatureApparentMin
       [...]
      forecast_observations: 3
      timestep: "1d"
      name: "Daily"
```
The strange thing is that I only get different values for d2. d0 and d1 are the same. But I get the same result when using the API via the [api documentation](https://docs.climacell.co/reference/retrieve-timelines-basic). It might be a coincidence or there is an error in the API.
