### ISSUE TITLE
Not Receiving wind information since migrating to v4 API

### ISSUE THREAD

**Issue by clarsonJWU** [r-renato/ha-climacell-weather#50]
I am not getting and wind information. My sensors report unknown for wind direction and 0 for speed and gust. Here is my config

```
- platform: climacell
  api_key: !secret climacell_api_v4
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  units: imperial
  timelines:
    - name: ""
      timestep: "1m"
      forecast_observations: 1
      fields:
        - weather_condition
        - temperatureMax
        - feels_like
        - humidity
        - wind_speed
        - wind_direction
        - wind_gust
        - pressure
        - precipitationIntensity
        - precipitation_type
        - visibility
        - cloud_cover
      update: auto
      scan_interval:
        # At least one of these must be specified:
        days: 0
        hours: 0
        minutes: 5
        seconds: 0
        milliseconds: 0
    - name: "Forecast"
      timestep: "1d"
      forecast_observations: 6
      fields:
        - temperatureMin
        - temperatureMax
        - precipitationIntensityMin
        - precipitationIntensityMax
        - precipitation_probability
        - weather_condition
      scan_interval:
        # At least one of these must be specified:
        days: 0
        hours: 4
        minutes: 0
        seconds: 0
        milliseconds: 0
```
